/**
 * Hermes agent hook injection.
 *
 * Writes a bash status-report script under `<hermesHome>/hooks/` and
 * registers it in config.yaml `hooks:` plus the shell-hooks allowlist.
 * Provides symmetric inject / remove helpers and a generic per-agent-hook
 * apply / remove pair for use by the local-agent pipeline (wired in a later
 * batch).
 */

import path from 'node:path';
import { chmod } from 'node:fs/promises';
import { generatedFileState, writeIfChanged, pathExists, remove } from './utils/fs.js';
import { log } from './utils/logger.js';
import { getHermesHome } from './hermes-home.js';
import {
  upsertHermesHook,
  removeHermesHookByCommand,
  addHermesAllowlist,
  removeHermesAllowlist,
  enableHermesPlugin,
  disableHermesPlugin,
} from './hermes-config.js';

/** Hermes hook event used for session-start status reporting. */
const REPORT_EVENT = 'on_session_start';

/** Name of teamai's Hermes plugin, also its `plugins.enabled` entry. */
export const HERMES_INSTRUCTIONS_PLUGIN = 'teamai-instructions';

/**
 * Characters Hermes allows one plugin prompt section. A larger section is
 * skipped, so teamai reports it rather than truncating the instructions.
 */
export const HERMES_SECTION_LIMIT = 4000;

/** Directory of teamai's Hermes plugin. */
export function getInstructionsPluginDir(): string {
  return path.join(getHermesHome(), 'plugins', HERMES_INSTRUCTIONS_PLUGIN);
}

const PLUGIN_MARKER = '# [teamai] generated by teamai';

/**
 * Whether teamai may write or delete the plugin directory: it does not exist
 * yet, or its manifest carries teamai's marker. A same-named plugin of the
 * member's is never overwritten or removed.
 */
export async function ownsInstructionsPlugin(): Promise<boolean> {
  const dir = getInstructionsPluginDir();
  if (!await pathExists(dir)) return true;
  return await generatedFileState(path.join(dir, 'plugin.yaml'), PLUGIN_MARKER) === 'teamai';
}

/** Why teamai left the plugin directory alone, and what to do. */
export function foreignInstructionsPlugin(): string {
  return `${getInstructionsPluginDir()} holds a plugin teamai did not write, so teamai left it unchanged and Hermes sessions in a project `
    + 'get no team instructions. Rename or move that plugin, then run `teamai hooks inject`.';
}

/**
 * The plugin adds the member's team instructions for the session's project
 * as a cache-safe system prompt section (#945). Hermes builds the section
 * once for a new session and keeps it through compression and resume.
 * Outside a project `hook-dispatch instructions` prints nothing and the
 * section is empty: the user-scope blocks are in SOUL.md.
 */
export function buildInstructionsPlugin(): { manifest: string; init: string } {
  const manifest = [
    `${PLUGIN_MARKER}, do not edit.`,
    `name: ${HERMES_INSTRUCTIONS_PLUGIN}`,
    'version: "1"',
    'description: Adds the team instructions teamai resolves for this member and project.',
    '',
  ].join('\n');
  const init = [
    '"""[teamai] team instructions plugin, generated by teamai, do not edit."""',
    'import json',
    'import os',
    'import shutil',
    'import subprocess',
    '',
    '',
    'def _instructions(session_info):',
    '    cwd = session_info.get("cwd") or os.getcwd()',
    '    try:',
    '        result = subprocess.run(',
    '            [shutil.which("teamai") or "teamai", "hook-dispatch", "instructions", "--tool", "hermes"],',
    '            input=json.dumps({"cwd": cwd, "session_id": session_info.get("session_id")}),',
    '            capture_output=True,',
    '            text=True,',
    '            cwd=cwd,',
    '            timeout=15,',
    '        )',
    '        out = result.stdout.strip()',
    '        text = json.loads(out)["hookSpecificOutput"]["additionalContext"] if out else ""',
    '    except Exception:',
    '        return ""',
    '    return text if isinstance(text, str) else ""',
    '',
    '',
    'def register(ctx):',
    '    ctx.register_system_prompt_section(',
    '        "teamai.instructions",',
    '        _instructions,',
    '        position="after_memory",',
    `        max_chars=${HERMES_SECTION_LIMIT},`,
    '    )',
    '',
  ].join('\n');
  return { manifest, init };
}

/** Absolute path to the generated status-report shell script. */
export function getReportScriptPath(): string {
  return path.join(getHermesHome(), 'hooks', 'teamai-status-report.sh');
}

/**
 * Return the content of the status-report shell script.
 * The script shells out to `teamai hook-dispatch` and swallows all errors so
 * it never blocks the agent session.
 */
function buildReportScript(): string {
  return [
    '#!/usr/bin/env bash',
    '# [teamai] status-report hook — generated by teamai, do not edit.',
    'teamai hook-dispatch session-start --tool hermes >/dev/null 2>&1 || true',
    '',
  ].join('\n');
}

/**
 * Inject (or refresh) the teamai Hermes status-report hook.
 *
 * Steps:
 * 1. Create the `hooks/` directory under the Hermes home.
 * 2. Write the shell script and mark it executable (0o755).
 * 3. Register the script in config.yaml `hooks.on_session_start`.
 * 4. Add the script path to the shell-hooks allowlist.
 */
export async function injectHermesHooks(): Promise<void> {
  const scriptPath = getReportScriptPath();
  const scriptChanged = await writeIfChanged(scriptPath, buildReportScript());
  try {
    await chmod(scriptPath, 0o755);
  } catch (e) {
    log.warn(`Failed to chmod Hermes hook script: ${(e as Error).message}`);
  }
  const hookChanged = await upsertHermesHook(REPORT_EVENT, { command: scriptPath, timeout: 60 });
  const allowlistChanged = await addHermesAllowlist(REPORT_EVENT, scriptPath);
  let pluginChanged = false;
  if (await ownsInstructionsPlugin()) {
    const plugin = buildInstructionsPlugin();
    const pluginDir = getInstructionsPluginDir();
    const manifestChanged = await writeIfChanged(path.join(pluginDir, 'plugin.yaml'), plugin.manifest);
    const initChanged = await writeIfChanged(path.join(pluginDir, '__init__.py'), plugin.init);
    const pluginEnabled = await enableHermesPlugin(HERMES_INSTRUCTIONS_PLUGIN);
    pluginChanged = manifestChanged || initChanged || pluginEnabled;
  } else {
    log.warn(`Skipping the Hermes instructions plugin: ${getInstructionsPluginDir()} exists without the TeamAI marker`);
  }
  if (scriptChanged || hookChanged || allowlistChanged || pluginChanged) {
    log.success('Injected teamai Hermes hook into ' + scriptPath);
  } else {
    log.debug(`teamai Hermes hook already up-to-date in ${scriptPath}`);
  }
}

/**
 * Remove the teamai Hermes status-report hook.
 *
 * Steps:
 * 1. Remove the script from config.yaml `hooks:`.
 * 2. Remove the script from the shell-hooks allowlist.
 * 3. Delete the script file if it exists.
 */
export async function removeHermesHooks(): Promise<void> {
  const scriptPath = getReportScriptPath();
  await removeHermesHookByCommand(scriptPath);
  await removeHermesAllowlist(REPORT_EVENT, scriptPath);
  if (await pathExists(scriptPath)) {
    await remove(scriptPath);
  }
  if (await ownsInstructionsPlugin()) {
    await disableHermesPlugin(HERMES_INSTRUCTIONS_PLUGIN);
    await remove(getInstructionsPluginDir());
  }
  log.success('Removed teamai Hermes hook from ' + scriptPath);
}

/**
 * Register a named agent hook entry in Hermes config.yaml and allowlist.
 *
 * @param def - Hook definition including a human-readable `slug` for logging.
 */
export async function applyHermesAgentHook(def: {
  slug: string;
  event: string;
  command: string;
  matcher?: string;
  timeout?: number;
}): Promise<void> {
  const entry: { command: string; matcher?: string; timeout?: number } = {
    command: def.command,
  };
  if (def.matcher !== undefined) entry.matcher = def.matcher;
  if (def.timeout !== undefined) entry.timeout = def.timeout;

  await upsertHermesHook(def.event, entry);
  await addHermesAllowlist(def.event, def.command);
  log.success(`Installed Hermes agent hook [${def.slug}]`);
}

/**
 * Remove a named agent hook entry from Hermes config.yaml and allowlist.
 *
 * @param opts - At minimum `command` is required; providing `event` also
 *   removes the allowlist entry for that specific `(event, command)` pair.
 */
export async function removeHermesAgentHook(opts: {
  slug: string;
  event?: string;
  command: string;
}): Promise<void> {
  await removeHermesHookByCommand(opts.command);
  if (opts.event !== undefined) {
    await removeHermesAllowlist(opts.event, opts.command);
  }
  log.success(`Removed Hermes agent hook [${opts.slug}]`);
}
